{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.amistad012oss.gradle",
    "module": "gradle-git-repo-plugin",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-git-repo-plugin-2.0.0.jar",
          "url": "gradle-git-repo-plugin-2.0.0.jar",
          "size": 27220,
          "sha512": "55c885f29b3cbaa7bbb775369e53afc8bcd17cd711e853a3702f581397787968a636a4d35b0e95c2321262de6705dcc410f49b1e80d71cc3735cf7cef1bea316",
          "sha256": "664651b4c1cbb41604d90582841b927c33f0166e04a37dbd22aa97a90d792bd3",
          "sha1": "dabcfcbdd891a7b707ec0ec1ac63b45850ff5323",
          "md5": "b6c58c52846336c42c7f59802813b11f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-git-repo-plugin-2.0.0.jar",
          "url": "gradle-git-repo-plugin-2.0.0.jar",
          "size": 27220,
          "sha512": "55c885f29b3cbaa7bbb775369e53afc8bcd17cd711e853a3702f581397787968a636a4d35b0e95c2321262de6705dcc410f49b1e80d71cc3735cf7cef1bea316",
          "sha256": "664651b4c1cbb41604d90582841b927c33f0166e04a37dbd22aa97a90d792bd3",
          "sha1": "dabcfcbdd891a7b707ec0ec1ac63b45850ff5323",
          "md5": "b6c58c52846336c42c7f59802813b11f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-git-repo-plugin-2.0.0-javadoc.jar",
          "url": "gradle-git-repo-plugin-2.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ee25c0d9c9a914c74c82111748d48bd9010996576112a39bf5f3f5c7ee025a978373856b5d72613f098a38306825f220a0b738893d3438ed2c9e4b0f7fcb01c5",
          "sha256": "0f25d60ee2a11919da3b7fb2d8f80d06e74e3a7272483bc66ffb225395e5099e",
          "sha1": "b993970244511942e4fcf4c33151826c07ebf76e",
          "md5": "c3b01296ac9bd6d6cc38df01a1f930d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-git-repo-plugin-2.0.0-sources.jar",
          "url": "gradle-git-repo-plugin-2.0.0-sources.jar",
          "size": 2526,
          "sha512": "19d872355f958b4e265053efbf3d6abee538ba791cd8f37343f5cd00501244cb8c9fd3cd741fc6cb5088429d3ee7f1f496ffa57748ad253997bc374ffe966afb",
          "sha256": "337eeadb1b93aa6e151a6ca38329de912f5fb68bdc2c5648acf7cea53b38430b",
          "sha1": "0e4ac0dff428fa6f3d315a0c05b1792cba230494",
          "md5": "3cba7ef6b7778268e9470b522841ed25"
        }
      ]
    }
  ]
}
