{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.amistad012oss.gradle",
    "module": "git-repo-plugin",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "git-repo-plugin-2.0.0.jar",
          "url": "git-repo-plugin-2.0.0.jar",
          "size": 27220,
          "sha512": "536b67e20a806ba3c3d8b947c409d8d47a119168c12bb46bc551cad97bde951f37ceccc653c4feedca15b1105e138dd53ebca773388db2a1c21308f9031e32c8",
          "sha256": "14af905a0b7e11d79d51ca301a0761fe6e6a6e91f1850ca4b0d8ce30eff2d326",
          "sha1": "7e6893c42434df093dc8a8d9bfe105c6e9a5e345",
          "md5": "8913ae08750c9da65a67fdd10f303f97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "git-repo-plugin-2.0.0.jar",
          "url": "git-repo-plugin-2.0.0.jar",
          "size": 27220,
          "sha512": "536b67e20a806ba3c3d8b947c409d8d47a119168c12bb46bc551cad97bde951f37ceccc653c4feedca15b1105e138dd53ebca773388db2a1c21308f9031e32c8",
          "sha256": "14af905a0b7e11d79d51ca301a0761fe6e6a6e91f1850ca4b0d8ce30eff2d326",
          "sha1": "7e6893c42434df093dc8a8d9bfe105c6e9a5e345",
          "md5": "8913ae08750c9da65a67fdd10f303f97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "git-repo-plugin-2.0.0-javadoc.jar",
          "url": "git-repo-plugin-2.0.0-javadoc.jar",
          "size": 261,
          "sha512": "7e63dad1a5ce397159c6dffe4a3acfde1bcb3b30a869ba35405cdac0516d834371bbbf9ad9a0df5758be4a0d61ae50c871c9847b7395cfa0c262a09ab21e66f4",
          "sha256": "1dbd9e207bbf101a09d725de2ac12dfb89ac11b1399b7588265d97ce1fdd342d",
          "sha1": "3c185f5fd04a26914fc75f913c08bf5325139ac7",
          "md5": "87bcccbbf94a155637025b26e7e09c3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "git-repo-plugin-2.0.0-sources.jar",
          "url": "git-repo-plugin-2.0.0-sources.jar",
          "size": 2526,
          "sha512": "3dfa12fbf4bfe05f8a9042b2854febb783d15dbe358a1a6fe0d035acab3a58d49fa246a53d873989829b58158d516e721ddbbd28e8088dd6dce69f1e3ca2d3cf",
          "sha256": "cddc69c9e1ff0b909d1ec289524c0f637ab86dba97db16b950fd63e00200cd7e",
          "sha1": "393b1ff3966b8f019cf8d112b17c7198eafd63dc",
          "md5": "2094d0342f894eded3d088667895ec14"
        }
      ]
    }
  ]
}
